### ISSUE TITLE
SQLReduce unable to reduce sql

### ISSUE THREAD

**Issue by robins** [robins/sqlreduce#2]
I couldn't run the first SQL that sqlsmith spewed out :( .

Can't dive deeper for now, but logging an issue before this is lost.

```
ubuntu@myip:~/proj/sqlreduce$ sqlreduce -d "$TCONNSTR" -f a.sql --debug
Traceback (most recent call last):
  File "/usr/bin/sqlreduce", line 11, in <module>
    load_entry_point('sqlreduce==1.0', 'console_scripts', 'sqlreduce')()
  File "/usr/lib/python3/dist-packages/sqlreduce/main.py", line 37, in sqlreduce_main
    min_query, state = sqlreduce.run_reduce(query,
  File "/usr/lib/python3/dist-packages/sqlreduce/__init__.py", line 1099, in run_reduce
    parsed_query = pglast.parse_sql(query)
  File "pglast/parser.pyx", line 276, in pglast.parser.parse_sql
pglast.parser.ParseError: syntax error at or near ";", at index 2295
ubuntu@myip:~/proj/sqlreduce$

ubuntu@myip:~/proj/sqlreduce$ psql -d postgres -h localhost
psql (15beta1)
Type "help" for help.

postgres=# \q
ubuntu@myip:~/proj/sqlreduce$ echo $TCONNSTR
host=localhost dbname=postgres user=ubuntu password=ubuntu
ubuntu@myip:~/proj/sqlreduce$

```

**Comment by robins** [comment]
My bad. It helps if the SQL is complete :( Closing this one out.
